// Auxiliary whitelist of bundled preview files known to exist on disk.
// Not the catalog source — cards use `previewAsset` / `previewAssets` from JSON.
// PreviewAssetImage still attempts any declared path and falls back on error.

class PreviewAssetRegistry {
  PreviewAssetRegistry._();

  /// Paths verified under `frontend/assets/previews/` (update when adding jpg/png).
  static const Set<String> availableAssets = {
    'assets/previews/photoshoots/business_portrait_1.jpg',
    'assets/previews/photoshoots/business_portrait_2.jpg',
    'assets/previews/photoshoots/business_portrait_3.jpg',
    'assets/previews/photoshoots/business_brand_1.jpg',
    'assets/previews/photoshoots/business_brand_2.jpg',
    'assets/previews/photoshoots/business_brand_3.jpg',
    'assets/previews/photoshoots/cafe_city_1.jpg',
    'assets/previews/photoshoots/cafe_city_2.jpg',
    'assets/previews/photoshoots/cafe_city_3.jpg',
    'assets/previews/photoshoots/evening_look_1.jpg',
    'assets/previews/photoshoots/evening_look_2.jpg',
    'assets/previews/photoshoots/evening_look_3.jpg',
    'assets/previews/photoshoots/expert_photoshoot_1.jpg',
    'assets/previews/photoshoots/expert_photoshoot_2.jpg',
    'assets/previews/photoshoots/expert_photoshoot_3.jpg',
    'assets/previews/photoshoots/home_portrait_1.jpg',
    'assets/previews/photoshoots/home_portrait_2.jpg',
    'assets/previews/photoshoots/home_portrait_3.jpg',
    'assets/previews/photoshoots/park_walk_1.jpg',
    'assets/previews/photoshoots/park_walk_2.jpg',
    'assets/previews/photoshoots/park_walk_3.jpg',
    'assets/previews/photoshoots/personal_brand_1.jpg',
    'assets/previews/photoshoots/personal_brand_2.jpg',
    'assets/previews/photoshoots/personal_brand_3.jpg',
    'assets/previews/photoshoots/premium_portrait_1.jpg',
    'assets/previews/photoshoots/premium_portrait_2.jpg',
    'assets/previews/photoshoots/premium_portrait_3.jpg',
    'assets/previews/photoshoots/studio_portrait_1.jpg',
    'assets/previews/photoshoots/studio_portrait_2.jpg',
    'assets/previews/photoshoots/studio_portrait_3.jpg',
    'assets/previews/photoshoots/summer_photoshoot_1.jpg',
    'assets/previews/photoshoots/summer_photoshoot_2.jpg',
    'assets/previews/photoshoots/summer_photoshoot_3.jpg',
    'assets/previews/photoshoots/tender_photoshoot_1.jpg',
    'assets/previews/photoshoots/tender_photoshoot_2.jpg',
    'assets/previews/photoshoots/tender_photoshoot_3.jpg',
    'assets/previews/photoshoots/travel_portrait_1.jpg',
    'assets/previews/photoshoots/travel_portrait_2.jpg',
    'assets/previews/photoshoots/travel_portrait_3.jpg',
    'assets/previews/photoshoots/urban_portrait_1.jpg',
    'assets/previews/photoshoots/urban_portrait_2.jpg',
    'assets/previews/photoshoots/urban_portrait_3.jpg',
    'assets/previews/photoshoots/winter_photoshoot_1.jpg',
    'assets/previews/photoshoots/winter_photoshoot_2.jpg',
    'assets/previews/photoshoots/winter_photoshoot_3.jpg',
    'assets/previews/templates/beautiful_portrait.jpg',
    'assets/previews/templates/bright_look.jpg',
    'assets/previews/templates/business_portrait.jpg',
    'assets/previews/templates/child_photo.jpg',
    'assets/previews/templates/clothes_photo.jpg',
    'assets/previews/templates/expert_look.jpg',
    'assets/previews/templates/family_photo.jpg',
    'assets/previews/templates/gentle_portrait.jpg',
    'assets/previews/templates/holiday_look.jpg',
    'assets/previews/templates/interior_photo.jpg',
    'assets/previews/templates/jewelry_photo.jpg',
    'assets/previews/templates/product_photo.jpg',
    'assets/previews/templates/profile_photo.jpg',
    'assets/previews/templates/resume_photo.jpg',
    'assets/previews/templates/social_photo.jpg',
    'assets/previews/templates/summer_portrait.jpg',
    'assets/previews/templates/winter_portrait.jpg',
    'assets/previews/templates/volcanic_gray_rock.jpg',
    'assets/previews/templates/ocean_portrait.jpg',
    'assets/previews/templates/beach_sand_portrait.jpg',
    'assets/previews/templates/white_dress_yellow_meadow.jpg',
    'assets/previews/templates/woman_with_cat.jpg',
    'assets/previews/templates/child_birthday_number.jpg',
    'assets/previews/templates/child_name_age.jpg',
    'assets/previews/templates/child_memory_birthday.jpg',
    'assets/previews/templates/birthday_balloons.jpg',
  };

  static bool isAvailable(String? assetPath) {
    if (assetPath == null || assetPath.isEmpty) return false;
    return availableAssets.contains(assetPath);
  }
}
